### PR TITLE
Added function to browse through all sections of an ini file

### PR DESCRIPTION
**Pull request by kaixxx**
Allows to browse through an ini file with an unknown number of sections which all contain the same elements. This can be useful to store different profiles which are selectable on the device. I use it for reflow profiles in my arduino controlled lab oven.
I have also added an example.

### CODE REVIEW

**Comment by stevemarple** [comment]
This looks useful but sadly the regression test fails to compile with this error:
```
IniFile.h:130:7: error: extra qualification ‘IniFile::’ on member ‘browseSections’ [-fpermissive]
  bool IniFile::browseSections(char* buffer, size_t len, IniFileState &state) const;
```

With the `IniFile::` qualification removed the regression test compiles and passes. It would be nice to see some a new regression test added to `extras/test`, probably based off of your `IniBrowserExample.ino` example but we can add that later.

Can you please fix the compile issue and update the pull request (ideally squishing the the commits into one)? You can also add your name to the end of the contributors list in the same format as used for the other names.

**Comment by kaixxx** [comment]
Sorry for the error. It compiled fine in Arduino so I didn't notice. 
Hiding my mistake by changing the initial commit is not possible in GitHub Desktop (which I use), so I made a second commit. I hope that's ok. 
Thank you very much for this great library! I am happy to contribute a little bit.
Best 
Kai

**Comment by stevemarple** [comment]
I squished your second commit into the first and merged into the master branch. I'd like to have a test for the new functionality so I'll not close this issue just yet - I think I can use your example code to generate and then I'll post back here.

**Comment by stevemarple** [comment]
I've modified the regression test program to include a test for the `browseSections()` function. This approach isn't as powerful as proper unit testing but it is a very convenient way to check that future changes don't inadvertently break or change existing behaviour and has caught bugs in the past.

**Comment by kaixxx** [comment]
Great! Thank you very much. 
I think this can be closed now.

**Comment by stevemarple** [comment]
Thank you very much for your contribution. I'll close the issue and bump the version number so that the changes can be downloaded via the Arduino IDE.

**Pull request closed without merging**
